server:
  port: 8081
  error:
    include-stacktrace: never

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: user-api
  application:
    name: user-api

logging:
  level:
    org.dmitri: DEBUG

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8000/eureka/
  instance:
    hostname: localhost
